import type { 
  CivilStatus, 
  Resident, 
  ResidentFilters, 
  ResidentFormInput, 
  ResidentGender, 
  ResidentStatus 
} from "./types";

export const STATUS_OPTIONS: Array<"All" | ResidentStatus> = ["All", "Active", "Inactive", "Deceased"];
export const GENDER_OPTIONS: Array<"All" | ResidentGender> = ["All", "Male", "Female", "LGBTQIA+", "Other"];
export const CIVIL_STATUS_OPTIONS: Array<"All" | CivilStatus> = ["All", "Single", "Married", "Widowed", "Separated"];
export const AGE_GROUP_OPTIONS = ["All", "Child", "Adult", "Senior"] as const;

export const PENDING_RESIDENTS_KEY = "brgy-pending-residents";

export const SECTOR_OPTIONS = [
  "Senior Citizen",
  "Persons with Disability",
  "Solo Parent",
  "Displaced Worker",
  "Indigenous People",
  "Indigent Person",
  "Informal Settlers",
  "4Ps Beneficiary",
  "Farmer",
  "Nano/Micro Entrepreneur",
  "Student",
  "OFW",
  "TODA Driver",
  "JODA Driver",
  "Other Drivers",
  "Vendor",
  "With Comorbidities",
  "Working Student",
  "LGBTQIA+",
] as const;

export const SEED_RESIDENTS: Resident[] = [
  {
    id: "RES-2026-0001",
    firstName: "Maria",
    middleName: "Lopez",
    lastName: "Santos",
    birthdate: "1962-04-12",
    gender: "Female",
    civilStatus: "Married",
    address: "Purok 1, Brgy. Salaza",
    contactNumber: "09171234567",
    email: "maria.santos@example.com",
    status: "Active",
    tags: { senior: true, pwd: false, voter: true },
    dateRegistered: "2023-01-15",
    lastUpdated: "2026-04-12",
    householdInfo: "Household #H-102, 4 members",
    documentHistory: ["Barangay Clearance - Jan 2026", "Residency Certificate - Dec 2025"],
    requestHistory: ["Requested business permit endorsement - Feb 2026"],
  },
  {
    id: "RES-2026-0002",
    firstName: "Juan",
    middleName: "Reyes",
    lastName: "Dela Cruz",
    birthdate: "1998-11-03",
    gender: "Male",
    civilStatus: "Single",
    address: "Purok 2, Brgy. Salaza",
    contactNumber: "09981234567",
    email: "juan.delacruz@example.com",
    status: "Active",
    tags: { senior: false, pwd: false, voter: true },
    dateRegistered: "2024-02-04",
    lastUpdated: "2026-03-29",
    householdInfo: "Household #H-220, 3 members",
    documentHistory: ["NBI Referral - Mar 2026"],
    requestHistory: ["Requested indigency certificate - Mar 2026"],
  },
  {
    id: "RES-2026-0003",
    firstName: "Ana",
    middleName: "Garcia",
    lastName: "Reyes",
    birthdate: "1985-07-18",
    gender: "Female",
    civilStatus: "Married",
    address: "Purok 3, Brgy. Salaza",
    status: "Inactive",
    tags: { senior: false, pwd: true, voter: true },
    dateRegistered: "2022-05-21",
    lastUpdated: "2026-01-09",
    documentHistory: ["PWD Verification - Jan 2026"],
    requestHistory: ["Updated profile details - Jan 2026"],
  },
  {
    id: "RES-2026-0004",
    firstName: "Pedro",
    middleName: "Cruz",
    lastName: "Luna",
    birthdate: "1948-02-02",
    gender: "Male",
    civilStatus: "Widowed",
    address: "Purok 1, Brgy. Salaza",
    status: "Active",
    tags: { senior: true, pwd: true, voter: true },
    dateRegistered: "2021-08-10",
    lastUpdated: "2026-03-02",
    documentHistory: ["Senior Citizen Certification - Mar 2026"],
    requestHistory: ["Medicine assistance request - Feb 2026"],
  },
  {
    id: "RES-2026-0005",
    firstName: "Carla",
    middleName: "Mendoza",
    lastName: "Rivera",
    birthdate: "2009-10-22",
    gender: "Female",
    civilStatus: "Single",
    address: "Purok 4, Brgy. Salaza",
    status: "Active",
    tags: { senior: false, pwd: false, voter: false },
    dateRegistered: "2025-08-01",
    lastUpdated: "2026-04-01",
    documentHistory: ["School Residency Request - Apr 2026"],
    requestHistory: ["Requested student certificate - Apr 2026"],
  },
  {
    id: "RES-2026-0006",
    firstName: "Liza",
    middleName: "Torres",
    lastName: "Gonzales",
    birthdate: "1992-03-14",
    gender: "Female",
    civilStatus: "Separated",
    address: "Purok 5, Brgy. Salaza",
    status: "Deceased",
    tags: { senior: false, pwd: false, voter: true },
    dateRegistered: "2020-06-18",
    lastUpdated: "2025-12-20",
    documentHistory: ["Civil registry update - Dec 2025"],
    requestHistory: ["Status archived - Dec 2025"],
  },
  {
    id: "RES-2026-0007",
    firstName: "Mark",
    middleName: "Lim",
    lastName: "Aquino",
    birthdate: "2001-09-05",
    gender: "Male",
    civilStatus: "Single",
    address: "Purok 2, Brgy. Salaza",
    status: "Active",
    tags: { senior: false, pwd: false, voter: true },
    dateRegistered: "2024-11-07",
    lastUpdated: "2026-04-14",
    documentHistory: ["Barangay ID Renewal - Apr 2026"],
    requestHistory: ["Requested certificate of residency - Apr 2026"],
  },
  {
    id: "RES-2026-0008",
    firstName: "Rosa",
    middleName: "Diaz",
    lastName: "Navarro",
    birthdate: "1959-01-30",
    gender: "Female",
    civilStatus: "Married",
    address: "Purok 3, Brgy. Salaza",
    status: "Active",
    tags: { senior: true, pwd: false, voter: true },
    dateRegistered: "2023-09-09",
    lastUpdated: "2026-04-03",
    documentHistory: ["Senior validation - Apr 2026"],
    requestHistory: ["Requested livelihood support - Mar 2026"],
  },
];

export const EMPTY_FILTERS: ResidentFilters = {
  status: "All",
  gender: "All",
  civilStatus: "All",
  ageGroup: "All",
  seniorOnly: false,
  pwdOnly: false,
  voterOnly: false,
  registeredFrom: "",
  registeredTo: "",
};

export const EMPTY_FORM: ResidentFormInput = {
  firstName: "",
  middleName: "",
  lastName: "",
  profilePhotoName: "",
  birthdate: "",
  placeOfBirth: "",
  gender: "Male",
  headOfHousehold: "No",
  residenceType: "Village",
  address: "",
  province: "",
  cityMunicipality: "",
  barangay: "",
  street: "",
  blockLot: "",
  houseNo: "",
  typeOfResident: "",
  contactNumber: "",
  email: "",
  civilStatus: "Single",
  employmentStatus: "",
  citizenship: "",
  religion: "",
  precinctNo: "",
  bloodType: "",
  sectors: [],
  organDonor: "No",
  healthHistory: "",
  educationalAttainments: [
    {
      level: "",
      course: "",
      school: "",
      startYear: "",
      endYear: "",
      currentlyStudying: false,
    },
  ],
  workExperiences: [
    {
      position: "",
      companyName: "",
      employmentType: "",
      startYear: "",
      endYear: "",
      jobDescription: "",
    },
  ],
  gsisSssNo: "",
  gsisSssExpiration: "",
  philHealthNo: "",
  philHealthExpiration: "",
  pagIbigNo: "",
  pagIbigExpiration: "",
  tinNo: "",
  tinExpiration: "",
  pwdId: "",
  pwdIdExpiration: "",
  seniorCitizenId: "",
  votersNo: "",
  barangayPosition: "",
  barangayRoleStartDate: "",
  barangayRoleEndDate: "",
  emergencyFullName: "",
  emergencyContactNo: "",
  emergencyAddress: "",
  thumbmarkFileName: "",
  tags: { senior: false, pwd: false, voter: false },
  householdInfo: "",
  latitude: "",
  longitude: "",
};
