import type { VawcCase } from "./types";

export const MOCK_VAWC_CASES: VawcCase[] = [
  {
    id: "VAWC-2026-001",
    survivorAlias: "Survivor A",
    respondentAlias: "Respondent A",
    caseType: "Psychological Abuse",
    riskLevel: "High",
    status: "For Interview",
    dateReported: "2026-04-18",
    nextActionDate: "2026-05-01",
    protectionOrder: "BPO Drafted",
    assignedOfficer: "VAWC Officer Ramos",
    referralPartner: "MSWDO",
    summary: "Survivor reported repeated threats and coercive control at home.",
    safetyPlan: [
      "Schedule private intake interview with social worker.",
      "Coordinate barangay tanod escort for urgent visits.",
      "Prepare BPO issuance requirements.",
    ],
    updatedAt: "2026-04-27",
  },
  {
    id: "VAWC-2026-002",
    survivorAlias: "Survivor B",
    respondentAlias: "Respondent B",
    caseType: "Economic Abuse",
    riskLevel: "Moderate",
    status: "For Referral",
    dateReported: "2026-04-10",
    nextActionDate: "2026-04-30",
    protectionOrder: "None",
    assignedOfficer: "VAWC Officer Dela Cruz",
    referralPartner: "PAO / Legal Aid",
    summary: "Reported withholding of financial support and document control.",
    safetyPlan: [
      "Refer for legal consultation and rights orientation.",
      "Issue barangay mediation invitation with safeguards.",
    ],
    updatedAt: "2026-04-25",
  },
  {
    id: "VAWC-2026-003",
    survivorAlias: "Survivor C",
    respondentAlias: "Respondent C",
    caseType: "Child Neglect",
    riskLevel: "Critical",
    status: "Open",
    dateReported: "2026-04-28",
    nextActionDate: "2026-04-29",
    protectionOrder: "BPO Issued",
    assignedOfficer: "VAWC Officer Luna",
    referralPartner: "CSWDO / PNP WCPD",
    summary: "Urgent report involving child neglect and unsafe household conditions.",
    safetyPlan: [
      "Immediate welfare check with social worker and WCPD.",
      "Secure temporary child protection referral.",
      "Document evidence and timeline for formal case handling.",
    ],
    updatedAt: "2026-04-28",
  },
  {
    id: "VAWC-2026-004",
    survivorAlias: "Survivor D",
    respondentAlias: "Respondent D",
    caseType: "Physical Abuse",
    riskLevel: "Low",
    status: "Closed",
    dateReported: "2026-03-14",
    nextActionDate: "2026-03-20",
    protectionOrder: "BPO Issued",
    assignedOfficer: "VAWC Officer Ramos",
    referralPartner: "Barangay Health Unit",
    summary: "Case resolved with completed safety interventions and closure review.",
    safetyPlan: [
      "Post-case wellness check after 30 days.",
      "Continue optional counseling sessions.",
    ],
    updatedAt: "2026-03-22",
  },
];
