import type { GadPlan } from "./types";

export const MOCK_GAD_PLANS: GadPlan[] = [
  {
    id: "GAD-2026-001",
    planTitle: "Women Leadership and Livelihood Training",
    description: "Capacity-building sessions for women leaders and livelihood groups.",
    targetBeneficiaries: "Women associations in all puroks",
    budgetAllocation: 180000,
    year: 2026,
    status: "Approved",
    dateCreated: "2026-02-12",
    lastUpdated: "2026-03-02",
    attachmentName: "gad-plan-leadership.pdf",
  },
  {
    id: "GAD-2026-002",
    planTitle: "VAWC Awareness and Referral Strengthening",
    description: "Community awareness drives and referral protocol reinforcement.",
    targetBeneficiaries: "Families, youth groups, VAWC volunteers",
    budgetAllocation: 120000,
    year: 2026,
    status: "Submitted",
    dateCreated: "2026-03-18",
    lastUpdated: "2026-04-02",
  },
  {
    id: "GAD-2025-007",
    planTitle: "Gender-Sensitive Disaster Preparedness Workshops",
    description: "Preparedness modules tailored for women, children, and senior citizens.",
    targetBeneficiaries: "At-risk households in flood-prone areas",
    budgetAllocation: 95000,
    year: 2025,
    status: "Implemented",
    dateCreated: "2025-06-20",
    lastUpdated: "2025-10-11",
    attachmentName: "gad-disaster-workshop-report.xlsx",
  },
  {
    id: "GAD-2026-003",
    planTitle: "Gender Mainstreaming in Barangay Services",
    description: "Review and improve frontline services with gender-responsive standards.",
    targetBeneficiaries: "Barangay frontline offices and residents",
    budgetAllocation: 80000,
    year: 2026,
    status: "Draft",
    dateCreated: "2026-04-10",
    lastUpdated: "2026-04-10",
  },
];
