import type { AuditLog } from "./types";

export const MOCK_AUDIT_LOGS: AuditLog[] = [
  {
    id: "LOG-001",
    timestamp: "2026-04-29T08:12:00+08:00",
    userName: "Rogelio Ramos",
    role: "Admin",
    action: "Login",
    module: "Authentication",
    description: "User signed in to admin dashboard.",
    severity: "Info",
    ipAddress: "192.168.1.12",
    device: "Chrome on Windows",
  },
  {
    id: "LOG-002",
    timestamp: "2026-04-29T09:01:00+08:00",
    userName: "Liza Santos",
    role: "Secretary",
    action: "Create Record",
    module: "Residents",
    description: "Created new resident profile RES-2026-0142.",
    severity: "Info",
    affectedRecord: "RES-2026-0142",
  },
  {
    id: "LOG-003",
    timestamp: "2026-04-29T09:25:00+08:00",
    userName: "Ana Reyes",
    role: "Treasurer",
    action: "Finance Change",
    module: "Finance Management",
    description: "Updated disbursement amount for DIS-002.",
    severity: "Warning",
    affectedRecord: "DIS-002",
    oldValue: "175000",
    newValue: "185000",
  },
  {
    id: "LOG-004",
    timestamp: "2026-04-29T10:10:00+08:00",
    userName: "IT Admin",
    role: "Admin",
    action: "Settings Change",
    module: "System Settings",
    description: "Changed document number format in system settings.",
    severity: "Critical",
    oldValue: "DOC-{YEAR}-{SERIES}",
    newValue: "BRGY-{YEAR}-{SERIES}",
  },
  {
    id: "LOG-005",
    timestamp: "2026-04-29T10:35:00+08:00",
    userName: "Mark Dela Cruz",
    role: "Staff",
    action: "Generate Report",
    module: "Reports",
    description: "Generated and exported Barangay Annual Report 2026.",
    severity: "Info",
  },
  {
    id: "LOG-006",
    timestamp: "2026-04-29T11:02:00+08:00",
    userName: "Rogelio Ramos",
    role: "Admin",
    action: "Approve Request",
    module: "Requests",
    description: "Approved business permit request REQ-2026-091.",
    severity: "Warning",
    affectedRecord: "REQ-2026-091",
  },
  {
    id: "LOG-007",
    timestamp: "2026-04-29T11:30:00+08:00",
    userName: "Liza Santos",
    role: "Secretary",
    action: "Delete Record",
    module: "Documents",
    description: "Removed duplicate generated document DOC-ROW-8891.",
    severity: "Critical",
    affectedRecord: "DOC-ROW-8891",
  },
  {
    id: "LOG-008",
    timestamp: "2026-04-29T12:05:00+08:00",
    userName: "Rogelio Ramos",
    role: "Admin",
    action: "Logout",
    module: "Authentication",
    description: "User signed out from admin dashboard.",
    severity: "Info",
    ipAddress: "192.168.1.12",
    device: "Chrome on Windows",
  },
];
