import type { PersonnelRecord } from "./types";

export const MOCK_PERSONNEL: PersonnelRecord[] = [
  {
    id: "PER-001",
    fullName: "Rogelio Ramos",
    employeeNumber: "EMP-2022-001",
    position: "Punong Barangay",
    office: "Office of the Punong Barangay",
    type: "Elected",
    status: "Active",
    dateAppointed: "2022-07-01",
    contactNumber: "0917-440-1122",
    emailAddress: "r.ramos@brgysalaza.gov.ph",
    address: "Purok 2, Brgy. Salaza",
    attachmentName: "appointment-paper-ramos.pdf",
  },
  {
    id: "PER-002",
    fullName: "Liza Santos",
    employeeNumber: "EMP-2023-015",
    position: "Barangay Secretary",
    office: "Secretariat",
    type: "Appointed",
    status: "Active",
    dateAppointed: "2023-01-10",
    contactNumber: "0928-551-3390",
    emailAddress: "l.santos@brgysalaza.gov.ph",
    address: "Purok 1, Brgy. Salaza",
  },
  {
    id: "PER-003",
    fullName: "Mark Dela Cruz",
    employeeNumber: "EMP-2024-027",
    position: "Administrative Aide",
    office: "Admin Office",
    type: "Staff",
    status: "Inactive",
    dateAppointed: "2024-03-18",
    contactNumber: "0935-660-1822",
    emailAddress: "m.delacruz@brgysalaza.gov.ph",
    address: "Purok 4, Brgy. Salaza",
    attachmentName: "personnel-clearance-delacruz.pdf",
  },
  {
    id: "PER-004",
    fullName: "Ana Garcia Reyes",
    employeeNumber: "EMP-2021-009",
    position: "Treasurer",
    office: "Treasury",
    type: "Appointed",
    status: "Active",
    dateAppointed: "2021-09-02",
    contactNumber: "0908-773-1102",
    emailAddress: "a.reyes@brgysalaza.gov.ph",
    address: "Purok 3, Brgy. Salaza",
  },
];
